package helpers

const (
	SERVER_PORT = "SERVER_PORT"
	DB_USERNAME = "DB_USERNAME"
	DB_PASSWORD = "DB_PASSWORD"
	DB_PROTOCOL = "DB_PROTOCOL"
	DB_NAME     = "DB_NAME"
	DB_HOST     = "DB_HOST"
	DB_PORT     = "DB_PORT"
)
